- hosts: all
  vars_prompt:
          - name: container
            private: no
            prompt: "enter the name of docker container you want to launch"
          - name: port_number
            private: no
            prompt: "enter the port no you want to assign to this docker container"
  tasks:
   - name: configuring yum for docker
     yum_repository:
      name: docker_repo
      baseurl: https://download.docker.com/linux/centos/7/x86_64/stable/
      enabled: yes
      gpgcheck: no
      description: repos for docker
   - name: installing docker
     package:
      name: "docker-ce-18.09.1-3.el7.x86_64"
      state: present
   - name: installing python
     package:
      name: python3
      state: present


   - name: installing python dependencies for docker
     pip:
      name: docker-py


   - name: starting docker services
     service:
      name: "docker"
      state: started
      enabled: yes


   - name: pulling docker image for apache webserver
     community.general.docker_image:
      name: httpd
      source: pull

 - name: Creting the directory to keep hosting web pages
     file:
      path: "/httpd"
      state: directory


   - name: Copying the webpages to deploy
     copy:
      dest: "/httpd/index.html"
      content: >
                "Hello from the web server deployed at docker container using ansible!!!"


   - name: launching the container
     docker_container:
      name: "{{ container }}"
      image: httpd
      state: started
      exposed_ports: "80"
      published_ports: "{{ port_number }}:80"
      volumes: /httpd:/usr/local/apache2/htdocs/
   - name: Adding interface for docker traffic
     become: true
     firewalld:
      permanent: yes
      immediate: yes
      zone: trusted
      interface: docker0
      state: enabled
   - name: customizing firewall for docker
     firewalld:
      port: "{{ port_number }}/tcp"
      state: enabled
      permanent: yes
      immediate: yes
                               
